function Get-DateFormat {
    'd: {0}' -f (Get-Date -format d)
    'D: {0}' -f (Get-Date -format D)
    'f: {0}' -f (Get-Date -format f)
    'F: {0}' -f (Get-Date -format F)
    'g: {0}' -f (Get-Date -format g)
    'G: {0}' -f (Get-Date -format G)
    'm: {0}' -f (Get-Date -format m)
    'o: {0}' -f (Get-Date -format o)
    'r: {0}' -f (Get-Date -format r)
    's: {0}' -f (Get-Date -format s)
    't: {0}' -f (Get-Date -format t)
    'T: {0}' -f (Get-Date -format T)
    'u: {0}' -f (Get-Date -format u)
    'U: {0}' -f (Get-Date -format U)
    'y: {0}' -f (Get-Date -format y)
    'd, %d: {0}' -f (Get-Date -format %d)
    'dd: {0}' -f (Get-Date -format dd)
    'ddd: {0}' -f (Get-Date -format ddd)
    'dddd: {0}' -f (Get-Date -format dddd)
    'f, %f: {0}' -f (Get-Date -format %f)
    'F, %F: {0}' -f (Get-Date -format %F)
    'ff: {0}' -f (Get-Date -format ff)
    'FF: {0}' -f (Get-Date -format FF)
    'fff: {0}' -f (Get-Date -format fff)
    'FFF: {0}' -f (Get-Date -format FFF)
    'ffff: {0}' -f (Get-Date -format ffff)
    'FFFF: {0}' -f (Get-Date -format FFFF)
    'fffff: {0}' -f (Get-Date -format fffff)
    'FFFFF: {0}' -f (Get-Date -format FFFFF)
    'ffffff: {0}' -f (Get-Date -format ffffff)
    'FFFFFF: {0}' -f (Get-Date -format FFFFFF)
    'fffffff: {0}' -f (Get-Date -format fffffff)
    'FFFFFFF: {0}' -f (Get-Date -format FFFFFFF)
    'gg: {0}' -f (Get-Date -format gg)
    'h, %h: {0}' -f (Get-Date -format %h)
    'H, %H: {0}' -f (Get-Date -format %H)
    'hh: {0}' -f (Get-Date -format hh)
    'HH: {0}' -f (Get-Date -format HH)
    # 'K: {0}' -f (Get-Date -format K)
    'm, %m: {0}' -f (Get-Date -format %m)
    'M, %M: {0}' -f (Get-Date -format %M)
    'mm: {0}' -f (Get-Date -format mm)
    'MM: {0}' -f (Get-Date -format MM)
    'MMM: {0}' -f (Get-Date -format MMM)
    'MMMM: {0}' -f (Get-Date -format MMMM)
    's, %s: {0}' -f (Get-Date -format %s)
    'ss: {0}' -f (Get-Date -format ss)
    't, %t: {0}' -f (Get-Date -format %t)
    'tt: {0}' -f (Get-Date -format tt)
    'y, %y: {0}' -f (Get-Date -format %y)
    'yy: {0}' -f (Get-Date -format yy)
    'yyy: {0}' -f (Get-Date -format yyy)
    'yyyy: {0}' -f (Get-Date -format yyyy)
    'yyyyy: {0}' -f (Get-Date -format yyyyy)
    'yyyyyy: {0}' -f (Get-Date -format yyyyyy)
    'z, %z: {0}' -f (Get-Date -format %z)
    'zz: {0}' -f (Get-Date -format zz)
    'zzz: {0}' -f (Get-Date -format zzz)
}